version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    privileged: true

  mongo:
    image: mongo
    ports:
      - 27017:27017
    privileged: true

  appserver:
    container_name: server
    hostname: localhost
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env

